{
 "title": "My dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "количество свободной оперативной памяти",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"nodeexporter:9100\"} "
    }
   ]
  },
  {
   "title": "утилизация CPU для nodeexporter",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance)(rate(node_cpu_seconds_total{instance=\"nodeexporter:9100\",mode=\"idle\"}[5m]))*100) "
    }
   ]
  },
  {
   "title": "количество места на файловой системе.",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=\"nodeexporter:9100\", mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"nodeexporter:9100\"}  "
    },
    {
     "expr": "node_load5{instance=\"nodeexporter:9100\"} "
    },
    {
     "expr": "node_load15{instance=\"nodeexporter:9100\"} "
    }
   ]
  }
 ]
}